touch .env
echo "REACT_APP_GOOGLE_MAP_API_KEY='${REACT_APP_GOOGLE_MAP_API_KEY}'" > .env
echo "REACT_APP_VISIT_KOREA_API_KEY='${REACT_APP_VISIT_KOREA_API_KEY}'" >> .env
echo "REACT_APP_WEATHER_API_KEY='${REACT_APP_WEATHER_API_KEY}'" >> .env
echo "REACT_APP_PIXABAY_API_KEY='${REACT_APP_PIXABAY_API_KEY}'" >> .env
echo "REACT_APP_TMAP_API_KEY='${REACT_APP_TMAP_API_KEY}'" >> .env
echo "APP_VERSION='${APP_VERSION}'" >> .env
cat .env
